import { Assistant, Rubik } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const geistSans = Assistant({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Rubik({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" dir="rtl" data-theme="light">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
