import "./globals.css";
import Navbar from "@/components/ui/Navbar";
import { Rubik, Varela_Round } from "next/font/google";

const fontSans = Rubik({
  subsets: ["hebrew", "latin"],
  variable: "--font-sans",
  weight: ["300", "400", "500", "700"],
});

const fontMono = Varela_Round({
  subsets: ["latin"],
  variable: "--font-mono",
  weight: "400",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="he" dir="rtl">
      <body className={`${fontSans.variable} ${fontMono.variable} antialiased`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
